#  ------------------------------
# |       HuskHomes Config       |
# |    Developed by William278   |
#  ------------------------------
# Configuration guide: https://github.com/WiIIiam278/HuskHomes2/wiki/Config-File

language: 'en-gb'
check_for_updates: true
data_storage_options:
  storage_type: 'SQLite'
  mysql_credentials:
    host: localhost
    port: 3306
    database: HuskHomes
    username: root
    password: pa55w0rd
    params: '?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull'
  connection_pool_options:
    maximum_pool_size: 10
    minimum_idle: 10
    maximum_lifetime: 1800000
    keepalive_time: 0
    connection_timeout: 5000
  table_names:
    player_data: 'huskhomes_player_data'
    locations_data: 'huskhomes_location_data'
    homes_data: 'huskhomes_home_data'
    warps_data: 'huskhomes_warp_data'
general:
  max_sethomes: 10
  auto_complete_player_names: true
  home_limit_permission_stacking: false
  teleport_warmup_time: 5
  teleport_request_expiry_time: 60
  allow_unicode_descriptions: true
  sounds:
    teleportation_complete: 'ENTITY_ENDERMAN_TELEPORT'
    teleportation_warmup: 'BLOCK_NOTE_BLOCK_BANJO'
    teleportation_cancelled: 'ENTITY_ITEM_BREAK'
  lists:
    private_homes_per_page: 10
    public_homes_per_page: 10
    warps_per_page: 10
  help_menu:
    hide_commands_without_permission: true
    hide_huskhomes_command: false
bungee_options:
  enable_bungee_mode: false
  server_id: 'server'
  cluster_id: 0
  messenger_type: 'pluginmessage'
  redis_credentials:
    host: localhost
    port: 6379
    password: ''
  tab_complete_cross_server:
    enabled: true
    delay: 60
warp_command:
  enabled: true
  permission_restrictions:
    require_permission: false
    format: 'huskhomes.warp.'
    hide_restricted_warps: true
spawn_command:
  enabled: true
  force_teleport_on_login: false
  bungee_network_spawn:
    enabled: false
    warp_name: 'Spawn'
random_teleport_command:
  enabled: true
  cooldown: 30
  range: 5000
map_integration:
  enabled: false
  plugin: 'dynmap'
  markers:
    public_homes:
      show: true
      set_name: 'Public Homes'
    warps:
      show: true
      set_name: 'Warps'
economy_integration:
  enabled: false
  free_home_slots: 5
  costs:
    additional_home_slot: 100
    make_home_public: 50
    random_teleport: 20
    back: 0
handle_vanished_players: true
config_file_version: 8